  domain: forgeops.com
  service:
    name: idm-service
    externalPort: 8080
    type: NodePort
  resources:
    requests:
      memory: "512Mi"
  config:
    strategy: files
    path: /opt/openidm
  openidm:
    repo:
      host: userstore-0.userstore
      port: 1389
      user: "uid=admin",
      password: password
